### ISSUE TITLE
Add a ReadME for the project

### ISSUE THREAD

**Issue by AyushTripathiIITP** [AyushTripathiIITP/ToDoList-v1.0#1]

**Comment by Mayank77maruti** [comment]
Hey @AyushTripathiIITP , Can you please assign this task to me under CodePeak'23 tag.

**Comment by Quaxguy** [comment]
Assign this task to me im a codedpeak23 contributor

**Comment by AyushTripathiIITP** [comment]
@Mayank77maruti @Quaxguy I am assigning both of you this task I will merge the best PR All the best

**Comment by YashSachan2** [comment]
Hi @AyushTripathiIITP , Can you please assign this task to me?

**Comment by Mayank77maruti** [comment]
Hi @AyushTripathiIITP , could you please tell how to run code locally.

**Comment by Mayank77maruti** [comment]
Hi @AyushTripathiIITP , I have made a pull request regarding readme file please do check it out.
