### ISSUE TITLE
404 page missing

### ISSUE THREAD

**Issue by Yash-Ainapure** [AyushTripathiIITP/ToDoList-v1.0#5]
I would like to add a "404 page not found" page . If the redirect url is not present then this page will be shown instead of showing errors on page which is not good for user experience
@AyushTripathiIITP 
the page i am talking about will look like this : 
![Screenshot (127)](https://github.com/AyushTripathiIITP/ToDoList-v1.0/assets/136250383/be550fed-0c14-4e8a-b064-03b3ed3d2756)

**Comment by AyushTripathiIITP** [comment]
go ahead @Yash-Ainapure

**Comment by Yash-Ainapure** [comment]
@AyushTripathiIITP , Could you check this pr please?
